name: Prueba AWS SSM - Royal Suites

on:
  push:
    branches:
      - aws-deploy
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar credenciales temporales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::213008104192:role/github-actions-royal-suites-deploy
          aws-region: us-east-2

      - name: Probar comunicación con EC2 mediante SSM
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "i-0e6a4e1a0f5eb9b93" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["docker pull bc377/angular-ssr-app:latest","docker stop royal-suites || true","docker rm royal-suites || true","docker run -d --name royal-suites -p 4000:4000 bc377/angular-ssr-app:latest","docker ps"]' \
            --query "Command.CommandId" \
            --output text)

          echo "Command ID: $COMMAND_ID"

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "i-0e6a4e1a0f5eb9b93"

          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "i-0e6a4e1a0f5eb9b93" \
            --query '{Estado:Status,Salida:StandardOutputContent,Error:StandardErrorContent}'