name: Build and Push Angular SSR Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Compilar Angular SSR
        run: npm run build:ssr

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build de imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/angular-ssr-app:latest .

      - name: Push de imagen Docker
        run: docker push ${{ secrets.DOCKER_USERNAME }}/angular-ssr-app:latest
