# Etapa 1: Construcción de Angular SSR
FROM node:20 AS builder

WORKDIR /app

# Copiar package.json e instalar dependencias
COPY package*.json ./
RUN npm install

# Copiar el resto del proyecto
COPY . .

# Construir la aplicación SSR (cliente + servidor)
RUN npm run build:ssr

# Etapa 2: Producción - Ejecutar la app SSR
FROM node:20-alpine AS runtime

WORKDIR /app

# Copiar el build generado desde la etapa anterior
COPY --from=builder /app/dist/PlataformaHotelFrontend /app

# Exponer el puerto (por defecto Angular Universal usa el 4000, pero puede cambiar)
EXPOSE 4000

# Comando para iniciar el servidor SSR
CMD ["node", "server/main.js"]
